export const SITE_URL = "https://www.khalil-am.com";
export const SITE_LAST_MODIFIED = "2026-09-10";

export const siteConfig = {
  name: "Khalil Abu Mushref",
  shortName: "Khalil AM",
  alternateNames: ["Khalil AM", "خليل أبو مشرف", "خليل ابو مشرف"],
  givenName: "Khalil",
  familyName: "Abu Mushref",
  title: "Khalil Abu Mushref | Principal Product Manager",
  description:
    "Official portfolio of Khalil Abu Mushref, Principal Product Manager and Product Owner at Digital Next, leading AI-enabled products across Riyadh and Abu Dhabi.",
  url: SITE_URL,
  jobTitle: "Principal Product Manager / Product Owner | Team Lead",
  employer: {
    name: "Digital Next",
    url: "https://digitalnext.io/",
  },
  location: {
    city: "Riyadh",
    country: "SA",
  },
  workLocations: [
    { city: "Riyadh", country: "SA" },
    { city: "Abu Dhabi", country: "AE" },
  ],
  email: "khalil-am@outlook.com",
  image: `${SITE_URL}/khalil.jpg`,
  socials: {
    linkedin: "https://linkedin.com/in/khalil-am",
    github: "https://github.com/Khalil-am",
    huggingFace: "https://huggingface.co/Khalil-am",
    indiePage: "https://indiepa.ge/khalilam",
  },
  keywords: [
    "Khalil Abu Mushref",
    "Principal Product Manager",
    "Product Owner",
    "Product Team Lead",
    "Product Management",
    "AI Product Strategy",
    "Digital Next",
    "IT Business Consultant",
    "Business Analyst",
    "AI Consultant",
    "Business Intelligence",
    "Power BI",
    "Data Science",
    "Digital Transformation",
    "Abu Dhabi",
    "United Arab Emirates",
    "Riyadh",
    "Saudi Arabia",
  ],
  expertise: [
    "Product Strategy",
    "Product Discovery",
    "Product Ownership",
    "AI Product Management",
    "AI Product Strategy",
    "Business Analysis",
    "Requirements Engineering",
    "Business Intelligence",
    "Data Products",
    "Delivery Governance",
    "Digital Transformation",
    "Enterprise Software",
    "Healthcare Technology",
    "Government Digital Services",
    "Fintech",
  ],
} as const;
